### ISSUE TITLE
Questions about bearing value in input

### ISSUE THREAD

**Issue by nomorewzx** [vlkryl/streetview_objectmapping#1]
Hi,

Thanks a lot for making your implementation public.

I have a question about "bearing" value in the input file. The README.md says:
> "bearing from north clockwise in degrees towards the object in the panoramic image", 

In the paper, I can only find one part about how to calculating the bearing value

> For each segmented region, a ray can be traced in the 3D space going from camera towards the barycenter of the segmented region".

Per my understanding, the bearing value is calculated based on the heading of Google Street View panorama and the ray that is traced in the 3D space, pls correct me if I am wrong.

I looked up how to trace the ray from camera to detected objects and still am clueless. Could you please tell me how do you trace the ray?  Thanks a lot.

**Comment by vlkryl** [comment]
Hi Wang,
It is assumed that a 90 degrees panoramic image with a central pixel oriented to 180 degrees (bearing towards south) will have the left-most column of pixels oriented to 180-90/2=135 degrees and right-most towards 180+90/2=225. It is also assumed that in the absence of optical distortions a vertical line in the image (or at least most of it in the centre of the image) will have the same bearing at all pixels. 
Under these assumptions the bearing towards any given pixel can be calculated proportionally to the width of the image.

**Comment by Vishnu-sai-teja** [comment]
This helps a lot , thank you @vlkryl 

but in some cases the bearing angle exeeds the limits you have mentioned above 

`51.509830,-0.136185,216.000000,5.000000
51.509830,-0.136185,289.000000,8.000000
51.509830,-0.136185,324.000000,4.200000
51.509856,-0.136014,113.000000,5.400000 `

greater than 225 , shouldn't that be your maximum possible bearing value ?
