### ISSUE TITLE
factor 640/256 in position conversions unexplained

### ISSUE THREAD

**Issue by rgommers** [vlkryl/streetview_objectmapping#4]
When reading in the data, the calculation for `latp, lonp` from `lat, lon` contains an unexplained factor 640/256 that doesn't seem to belong there. My best guess is that it's a correction factor for the depth estimate that's read in from the csv file, with 640 the number of pixels in the downloaded streetview panoramas, and 256 unclear (perhaps the pixel size of the images on which the monocular depth estimation model that you used was trained on?).

**Comment by vlkryl** [comment]
Yes, you are right. This scaling is **custom** to the depth estimator used in those experiments and originates from rescaling.
