### ISSUE TITLE
MRF energy calculation bug

### ISSUE THREAD

**Issue by rgommers** [vlkryl/streetview_objectmapping#5]
Consider the code [here](https://github.com/vlkryl/streetview_objectmapping/blob/master/objectmapping.py#L129):
```
   Energy = 0
   dpthmin, dpthmax = 1000, 0
   for i in range(len(ObjectsBase)) :
        ....
		if dpth<dpthmin:
			dpthmin = dpth
		if dpth>dpthmax:
			dpthmax = dpth
return Energy + ObjectMultiView*(dpthmax-dpthmin)
```
This says minimum depth is 1000, maximum depth is 0. Hence they're both set to the actual depth value, and `ObjectMultiView*(dpthmax-dpthmin)` is always zero. So the object multiview term is effectively disabled.

**Comment by vlkryl** [comment]
Hi Ralf,
In the for loop there is a line 
dpth = ObjectsDst[Object,i]
hence the dpthmin and dpthmax are estimating the minimum and maximum distances out of all intersections 'active' along this view ray. And then adds the corresponding contribution to the energy. So this part of code works as intended.
